media:
  input: docs/public/images
  output: /images
  rename: safe
  categories: [image]

actions:
  - name: create-pull-request
    label: Create PR to main
    workflow: pages-cms-create-pr.yml
    ref: current

content:
  - name: docs_ru
    label: Документация RU
    type: collection
    path: docs/ru
    format: yaml-frontmatter
    subfolders: true
    filename:
      template: "{primary}.md"
      field: create
    view:
      layout: tree
      node:
        filename: index.md
        hideDirs: nodes
      fields: [title]
      primary: title
      search: [title, body]
    fields:
      - name: title
        label: Заголовок
        type: string
        required: true
      - name: body
        label: Содержимое
        type: rich-text
        options:
          format: markdown
          switcher: true

  - name: docs_en
    label: Documentation EN
    type: collection
    path: docs/en
    format: yaml-frontmatter
    subfolders: true
    filename:
      template: "{primary}.md"
      field: create
    view:
      layout: tree
      node:
        filename: index.md
        hideDirs: nodes
      fields: [title]
      primary: title
      search: [title, body]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: body
        label: Content
        type: rich-text
        options:
          format: markdown
          switcher: true
